---
  - name: Deploy Application artifacts
    hosts: localhost
    gather_facts: true
    collections: 
      - ch_collections.base
    vars:
      artifact_name: "performance-analysis"
    roles:
      - name: ch_collections.base.cloudwatch_agent_config
        when: cw_log_files is defined
    tasks:
      - name: Get Local vars
        include_vars: deployment_vars.yml

      - name: Download the versioned release artifact from S3
        amazon.aws.aws_s3:
          bucket: "{{ s3_bucket_releases }}"
          object: "{{ artifact_name }}/{{ artifact_name }}-{{ version }}.zip"
          dest: "/tmp/{{ artifact_name }}-{{ version }}.zip"
          mode: get

      - name: Create temporary app folder for unzip
        ansible.builtin.file:
          path: "/tmp/{{ artifact_name }}-{{ version }}"
          state: directory
      
      - name: Unarchive the app artifact into its own folder
        ansible.builtin.unarchive:
          remote_src: yes
          src: "/tmp/{{ artifact_name }}-{{ version }}.zip"
          dest: "/tmp/{{ artifact_name }}-{{ version }}"
      
      - name: Move unarchived files and set permissions
        ansible.builtin.copy:
          src: "/tmp/{{ artifact_name }}-{{ version }}/"
          dest: "{{ http_root }}/"
          mode: u=rwX,g=rX,o=rX
          owner: "{{ httpd_user }}"
          group: "{{ httpd_group }}"
          remote_src: yes

      - name: Cleanup install files
        ansible.builtin.file:
          path: "{{ item }}"
          state: absent
        with_items:
          - "/tmp/{{ artifact_name }}-{{ version }}"
          - "/tmp/{{ artifact_name }}-{{ version }}.zip"

      - name: Ensure files are all owned and permissions are set correctly
        ansible.builtin.file:
          path: "{{ item }}"
          owner: "{{ httpd_user }}"
          group: "{{ httpd_group }}"
          mode: u=rwX,g=rX,o=rX
        loop:
          - /etc/httpd/conf/httpd.conf

      - name: Create Dirs
        ansible.builtin.file:
          path: "{{ item }}/"
          state: directory
          owner: metrics
          group: chlservices
          mode: '0755'
        loop:
          - "{{ http_root }}/dashboard/images"
          - "{{ http_root }}/dashboard/templates"
          - "{{ http_root }}/dashboard/static"
          - "{{ http_root }}/dashboard/static/style"
          - "{{ http_root }}/dashboard/static/help"
          - "{{ dashboard_json_data_dir }}"
      
      - name: Symlink common dependancies
        ansible.builtin.file:
          src: "{{ http_root }}/sitecommon/{{ item }}"
          path: "{{ http_root }}/dashboard/{{ item }}/com"
          owner: metrics
          group: chlservices
          state: link
          force: yes
        loop:
          - images
          - templates

      - name: Symlink common static dependancies
        ansible.builtin.file:
          src: "{{ http_root }}/sitecommon/{{ item }}"
          path: "{{ http_root }}/dashboard/static/{{ item }}/com"
          owner: metrics
          group: chlservices
          state: link
          force: yes
        loop:
          - style
          - help

      - name: Download the initial json data files from S3
        ansible.builtin.command:
          cmd: "/usr/bin/aws s3 sync --quiet s3://{{ s3_json_data_source_bucket }}{{ s3_json_data_source_path }} {{ dashboard_json_data_dir }}"

      - name: Setup Cron to sync json data files from S3 on schedule
        ansible.builtin.cron:
          name: "Sync json data files from S3"
          minute: "*/10"
          hour: "*"
          day: "*"
          month: "*"
          weekday: "*"
          job: "/usr/bin/aws s3 sync --quiet s3://{{ s3_json_data_source_bucket }}{{ s3_json_data_source_path }} {{ dashboard_json_data_dir }}"

      - name: Make sure Apache is started
        ansible.builtin.service:
          name: "httpd"
          state: started
          enabled: yes
